Repository mangabyte/surucursed, pull requests merged in 2025-04, with the labels that each got.

#2 Docs/configurações iniciais do projeto
  dev_tips.md
Labels: documentation

#11 docs: Adiciona referência dos autores e links diretos para as extensões
  dev_tips.md
Labels: bug

#4 feat: Implementação da mudança de posição da cobra
  game.c
Labels: enhancement

#18 feat: Implementação de verificação e amostra visual de quinas da cobra
  assets/bg.png
  assets/fruit.png
  assets/snake_body.png
  assets/snake_curve_i.png
  assets/snake_curve_o.png
  assets/snake_head.png
  assets/snake_tail.png
  constants.h
  dev_tips.md
  game.c
  game.h
  main.c
Labels: enhancement
